# Generated by Django 4.1.5 on 2023-02-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0004_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='choice',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_at',
        ),
    ]
